import { supabase } from "./supabase.js";

export async function getTemplates() {
  const { data, error } = await supabase
    .from("templates")
    .select("*")
    .order("position", { ascending: true })
    .order("created_at", { ascending: false });
  if (error) {
    console.error("Error fetching templates:", error);
    return [];
  }
  return data || [];
}

export async function getPublishedTemplates() {
  const { data, error } = await supabase
    .from("templates")
    .select("*")
    .eq("published", true)
    .order("position", { ascending: true })
    .order("created_at", { ascending: false });
  if (error) {
    console.error("Error fetching published templates:", error);
    return [];
  }
  return data || [];
}

export async function addTemplate(data) {
  const { data: result, error } = await supabase
    .from("templates")
    .insert([{
      title: data.title,
      category: data.category,
      type: data.type,
      image: data.image,
      video: data.video || "",
      prompt: data.prompt || "",
      published: false,
    }])
    .select()
    .single();
  if (error) {
    console.error("Error adding template:", error);
    return null;
  }
  return result;
}

export async function updateTemplate(id, data) {
  const { data: result, error } = await supabase
    .from("templates")
    .update({
      title: data.title,
      category: data.category,
      type: data.type,
      image: data.image,
      video: data.video || "",
      prompt: data.prompt || "",
    })
    .eq("id", id)
    .select()
    .single();
  if (error) {
    console.error("Error updating template:", error);
    return null;
  }
  return result;
}

export async function deleteTemplate(id) {
  const { error } = await supabase
    .from("templates")
    .delete()
    .eq("id", id);
  if (error) {
    console.error("Error deleting template:", error);
  }
}

export async function togglePublish(id) {
  const { data: result } = await supabase
    .from("templates")
    .update({ published: true })
    .eq("id", id)
    .neq("published", true)
    .select()
    .single();

  if (result) return result;

  const { data: unpublished, error: error2 } = await supabase
    .from("templates")
    .update({ published: false })
    .eq("id", id)
    .eq("published", true)
    .select()
    .single();

  if (error2) {
    console.error("Error toggling publish:", error2);
    return null;
  }
  return unpublished;
}

export async function incrementLikes(id) {
  const { data, error } = await supabase.rpc("increment_likes", { template_id: id });
  if (error) {
    console.error("Error incrementing likes:", error);
    return null;
  }
  return data;
}

export async function uploadImage(file) {
  const ext = file.name.split(".").pop();
  const fileName = `images/${Date.now()}-${Math.random().toString(36).slice(2, 9)}.${ext}`;
  const { error: uploadError } = await supabase.storage
    .from("templates")
    .upload(fileName, file, { cacheControl: "3600", upsert: false });
  if (uploadError) {
    console.error("Error uploading image:", uploadError);
    return null;
  }
  const { data: urlData } = supabase.storage.from("templates").getPublicUrl(fileName);
  return urlData.publicUrl;
}

export async function uploadVideo(file) {
  const ext = file.name.split(".").pop();
  const fileName = `videos/${Date.now()}-${Math.random().toString(36).slice(2, 9)}.${ext}`;
  const { error: uploadError } = await supabase.storage
    .from("templates")
    .upload(fileName, file, { cacheControl: "3600", upsert: false });
  if (uploadError) {
    console.error("Error uploading video:", uploadError);
    return null;
  }
  const { data: urlData } = supabase.storage.from("templates").getPublicUrl(fileName);
  return urlData.publicUrl;
}

export async function getTopLayouts() {
  const { data, error } = await supabase
    .from("top_layouts")
    .select("*")
    .order("position", { ascending: true });
  if (error) {
    console.error("Error fetching top layouts:", error);
    return [];
  }
  return data || [];
}

export async function saveTopLayouts(layouts) {
  // Delete all existing layouts (by matching IDs not equal to -1)
  const { error: deleteError } = await supabase
    .from("top_layouts")
    .delete()
    .neq("id", -1);

  if (deleteError) {
    console.error("Error deleting top layouts:", deleteError);
    return false;
  }

  if (layouts.length === 0) return true;

  // Insert new layouts mapping to exclude old autogenerated IDs
  const cleanLayouts = layouts.map((item, index) => ({
    title: item.title,
    template_ids: item.template_ids || [],
    position: index,
  }));

  const { error: insertError } = await supabase
    .from("top_layouts")
    .insert(cleanLayouts);

  if (insertError) {
    console.error("Error inserting top layouts:", insertError);
    return false;
  }
  return true;
}

export async function saveTemplatesOrder(templates) {
  const updates = templates.map((t, idx) =>
    supabase
      .from("templates")
      .update({ position: idx })
      .eq("id", t.id)
  );
  const results = await Promise.all(updates);
  const failed = results.find((r) => r.error);
  if (failed) {
    console.error("Error saving templates order:", failed.error);
    return false;
  }
  return true;
}

// ── User Profile ─────────────────────────────────────────────────

export async function getUserProfile(userId) {
  const { data, error } = await supabase
    .from("user_profiles")
    .select("*")
    .eq("id", userId)
    .single();
  if (error && error.code !== "PGRST116") {
    console.error("Error fetching user profile:", error);
    return null;
  }
  return data || null;
}

export async function createUserProfile(userId, email = "", fullName = "", avatarUrl = "") {
  const { data, error } = await supabase
    .from("user_profiles")
    .upsert({
      id: userId,
      email,
      full_name: fullName,
      avatar_url: avatarUrl,
      plan: "free"
    })
    .select()
    .single();
  if (error) {
    console.error("Error creating/checking user profile:", error);
    return null;
  }
  return data;
}

export async function updateUserPlan(userId, plan, razorpaySubscriptionId = null) {
  const { data, error } = await supabase
    .from("user_profiles")
    .upsert({
      id: userId,
      plan,
      razorpay_subscription_id: razorpaySubscriptionId,
      updated_at: new Date().toISOString(),
    })
    .select()
    .single();
  if (error) {
    console.error("Error updating user plan:", error);
    return null;
  }
  return data;
}

export async function captureVideoFirstFrame(videoSource, seekTime = 0.05) {
  return new Promise((resolve) => {
    if (!videoSource) {
      resolve(null);
      return;
    }
    const video = document.createElement("video");
    video.crossOrigin = "anonymous";
    video.muted = true;
    video.playsInline = true;
    video.preload = "auto";

    let objectUrl = null;
    if (videoSource instanceof File || videoSource instanceof Blob) {
      objectUrl = URL.createObjectURL(videoSource);
      video.src = objectUrl;
    } else if (typeof videoSource === "string" && videoSource.trim()) {
      video.src = videoSource.trim();
    } else {
      resolve(null);
      return;
    }

    let isCleanedUp = false;
    const cleanUp = () => {
      if (isCleanedUp) return;
      isCleanedUp = true;
      if (objectUrl) {
        URL.revokeObjectURL(objectUrl);
      }
      video.onloadeddata = null;
      video.onseeked = null;
      video.onerror = null;
      video.remove();
    };

    const captureCanvas = () => {
      try {
        const width = video.videoWidth || 640;
        const height = video.videoHeight || 360;
        if (!width || !height) {
          cleanUp();
          resolve(null);
          return;
        }
        const canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        ctx.drawImage(video, 0, 0, width, height);

        canvas.toBlob(
          (blob) => {
            cleanUp();
            resolve(blob);
          },
          "image/jpeg",
          0.88
        );
      } catch (err) {
        console.warn("Canvas capture error:", err);
        cleanUp();
        resolve(null);
      }
    };

    video.onloadeddata = () => {
      try {
        video.currentTime = Math.min(seekTime, (video.duration || 1) / 2);
      } catch {
        captureCanvas();
      }
    };

    video.onseeked = () => {
      captureCanvas();
    };

    video.onerror = (e) => {
      console.warn("Video loading error for thumbnail capture:", e);
      cleanUp();
      resolve(null);
    };

    setTimeout(() => {
      cleanUp();
      resolve(null);
    }, 10000);
  });
}

